language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "agistuck-github"
    token:
      secure: "bd0c64afc0342b09b764eb20a5367a5e50ca038c"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
